dataset_name: "results/preference_pairs_8_31/coco-speaker=gemma_pt-listener=gemma_ft-feedback_label=true-next=random"
output_dir: "/project/flame/svadugur/learning-conventions/models/coco-speaker=gemma_pt-listener=gemma_ft-feedback_label=true-next=random/ipo/lr=1e-5-ep=3-beta=0.3"
run_name: "coco-speaker=gemma_pt-listener=gemma_ft-feedback_label=true-next=random-ipo"
dataloader_num_workers: 8
dataloader_pin_memory: true
max_length: 16384
loss_type: "ipo"
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
use_peft: true
lora_target_modules: "all-linear"
lora_r: 32
lora_alpha: 32
gradient_checkpointing: true
agent_type: "speaker"
model_name_or_path: "google/gemma-3-12b-pt"
demonstration_game: "data/coco-4-image-contexts/demo.json"
bf16: true
learning_rate: 1e-5
beta: 0.3
gradient_accumulation_steps: 16
torch_dtype: "bfloat16"
eval_strategy: "steps"
eval_steps: 0.1
save_strategy: "steps"
save_steps: 0.1
save_total_limit: 5
logging_strategy: "steps"
logging_steps: 1
num_train_epochs: 3
warmup_ratio: 0.05
chat_template_file: "agents/gemma-3-pt-chat-template.jinja"
model_type: "base"
context_presentation: "once"
feedback_label: true
