experiment_configs:
  -
    games_path: lexgram/exp1_data-icca-no_control.json
    images_path: square-black-imgs
    model_name_or_path: HuggingFaceM4/Idefics3-8B-Llama3
    listener_type: generate
    listener_config:
      context_presentation: last_shuffle
    speaker_type: replay
    simulation_save_path: pixtral_results/speaker=human-listener=generate-context=last_shuffle.json
  -
    games_path: lexgram/exp1_data-icca-no_control.json
    images_path: square-black-imgs
    model_name_or_path: saujasv/pixtral-12b
    listener_type: generate
    listener_config:
      context_presentation: last_shuffle
    speaker_type: replay
    simulation_save_path: pixtral_results/speaker=human-listener=generate-context=last_shuffle.json
  -
    games_path: lexgram/exp1_data-icca-no_control.json
    images_path: square-black-imgs
    model_name_or_path: saujasv/pixtral-12b
    listener_type: joint_inference
    listener_config:
      listener_lambda: 0.5
      listener_context_presentation: last_shuffle
      speaker_context_presentation: last_shuffle
    speaker_type: replay
    simulation_save_path: pixtral_results/speaker=human-listener=joint_inference_tied-context=last_shuffle.json
  -
    games_path: lexgram/exp1_data-icca-no_control.json
    images_path: square-black-imgs
    model_name_or_path: saujasv/pixtral-12b
    listener_type: joint_inference
    listener_config:
      listener_lambda: 0.0
      listener_context_presentation: last_shuffle
      speaker_context_presentation: last_shuffle
    speaker_type: replay
    simulation_save_path: pixtral_results/speaker=human-listener=joint_inference_tied-context=last_shuffle-lambda=0.0.json
  -
    games_path: lexgram/exp1_data-icca-no_control.json
    images_path: square-black-imgs
    model_name_or_path: saujasv/pixtral-12b
    listener_type: joint_inference
    listener_config:
      listener_lambda: 1.0
      listener_context_presentation: last_shuffle
      speaker_context_presentation: last_shuffle
    speaker_type: replay
    simulation_save_path: pixtral_results/speaker=human-listener=joint_inference_tied-context=last_shuffle-lambda=1.0.json
  -
    games_path: lexgram/exp1_data-icca-no_control.json
    images_path: square-black-imgs
    model_name_or_path: saujasv/pixtral-12b
    listener_type: joint_inference
    listener_config:
      listener_lambda: 0.5
      listener_context_presentation: once
      speaker_context_presentation: once
    speaker_type: replay
    simulation_save_path: pixtral_results/speaker=human-listener=joint_inference_tied-context=once.json
  -
    games_path: lexgram/exp1_data-icca-no_control.json
    images_path: square-black-imgs
    model_name_or_path: saujasv/pixtral-12b
    listener_type: joint_inference
    listener_config:
      listener_lambda: 0.5
      listener_context_presentation: block_shuffle
      speaker_context_presentation: block_shuffle
    speaker_type: replay
    simulation_save_path: pixtral_results/speaker=human-listener=joint_inference_tied-context=block_shuffle.json
  -
    games_path: lexgram/exp1_data-icca-no_control.json
    images_path: square-black-imgs
    model_name_or_path: saujasv/pixtral-12b
    listener_type: joint_inference
    listener_config:
      listener_lambda: 0.5
      listener_context_presentation: last_shuffle
      speaker_context_presentation: last_shuffle
      speaker_prompt_type: explicit
    speaker_type: replay
    simulation_save_path: pixtral_results/speaker=human-listener=joint_inference_tied-context=last_shuffle-prompt_type=explicit.json
  -
    games_path: lexgram/exp1_data-icca-no_control.json
    images_path: square-black-imgs
    model_name_or_path: saujasv/pixtral-12b
    listener_type: joint_inference
    listener_config:
      listener_lambda: 0.5
      listener_context_presentation: last_shuffle
      speaker_context_presentation: last_shuffle
    speaker_type: joint_inference
    speaker_config:
      listener_context_presentation: last_shuffle
      speaker_context_presentation: last_shuffle
      num_speaker_samples: 10
      speaker_generation_config:
        temperature: 0.7
    simulation_save_path: pixtral_results/speaker=joint_inference_last_shuffle_tied-num_speaker_samples=10-listener=joint_inference_tied-context=last_shuffle.json
  -
    games_path: lexgram/exp1_data-icca-no_control.json
    images_path: square-black-imgs
    model_name_or_path: saujasv/pixtral-12b
    listener_type: joint_inference
    listener_config:
      listener_lambda: 0.5
      listener_context_presentation: last_shuffle
      speaker_context_presentation: last_shuffle
    speaker_type: joint_inference
    speaker_config:
      listener_context_presentation: once
      speaker_context_presentation: once
      num_speaker_samples: 10
      speaker_generation_config:
        temperature: 0.7
    simulation_save_path: pixtral_results/speaker=joint_inference_once_tied-num_speaker_samples=10-listener=joint_inference_tied-context=last_shuffle.json
  -
    games_path: lexgram/exp1_data-icca-no_control.json
    images_path: square-black-imgs
    model_name_or_path: saujasv/pixtral-12b
    listener_type: joint_inference
    listener_config:
      listener_lambda: 0.5
      listener_context_presentation: last_shuffle
      speaker_context_presentation: last_shuffle
    speaker_type: joint_inference
    speaker_config:
      listener_context_presentation: block_shuffle
      speaker_context_presentation: block_shuffle
      num_speaker_samples: 10
      speaker_generation_config:
        temperature: 0.7
    simulation_save_path: pixtral_results/speaker=joint_inference_block_shuffle_tied-num_speaker_samples=10-listener=joint_inference_tied-context=last_shuffle.json