dataset_name: "results/preference_pairs_9_26/coco-hard_correctness-speaker=pixtral_pt-listener=gemma_ft-feedback_label=true-next=random"
output_dir: "/data/tir/projects/tir3/users/svadugur/learning-conventions/models/coco-hard_correctness-speaker=pixtral_pt-listener=gemma_ft-feedback_label=true-next=random/ipo-eom/lr=1e-6-ep=3-beta=0.3"
run_name: "coco-hard_correctness-speaker=pixtral_pt-listener=gemma_ft-feedback_label=true-next=random-ipo"
dataloader_num_workers: 8
dataloader_pin_memory: true
max_length: 16384
loss_type: "ipo"
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
use_peft: true
lora_target_modules: "all-linear"
lora_r: 32
lora_alpha: 32
gradient_checkpointing: true
agent_type: "speaker"
model_name_or_path: "saujasv/pixtral-12b-base"
demonstration_game: "data/coco-4-image-contexts/demo-pixtral.json"
bf16: true
learning_rate: 1e-6
beta: 0.3
gradient_accumulation_steps: 8
torch_dtype: "bfloat16"
eval_strategy: "steps"
eval_steps: 0.1
save_strategy: "steps"
save_steps: 0.02
save_total_limit: 5
logging_strategy: "steps"
logging_steps: 1
num_train_epochs: 3
warmup_ratio: 0.05
chat_template_file: "agents/pixtral-pt-chat-template.jinja"
model_type: "base"
context_presentation: "once"
feedback_label: true
max_image_size: 256