dataset_name: /data/tir/projects/tir3/users/svadugur/learning-conventions/kilogram/base_model_training_games/kilogram-cogen_pretrain-4-images-listener
dataset_train_split: train
dataset_test_split: validation
output_dir: /data/tir/projects/tir3/users/svadugur/learning-conventions/models/kilogram-cogen_human_pretrain-listener-vision_tower-lora
run_name: kilogram-cogen_human_pretrain-listener-vision_tower-lora
agent_type: listener
model_type: base
context_presentation: last_shuffle
max_seq_length: 16384
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
use_peft: true
lora_target_modules: all-linear
gradient_checkpointing: true
model_name_or_path: /data/tir/projects/tir3/users/svadugur/learning-conventions/models/kilogram-cogen_human_pretrain-listener-vision_tower-no_shuffle/checkpoint-2817
chat_template_file: agents/gemma-3-pt-chat-template.jinja
bf16: true
learning_rate: 1.0e-5
gradient_accumulation_steps: 4
torch_dtype: bfloat16
eval_on_start: true
eval_strategy: epoch
eval_steps: 1
save_strategy: epoch
save_steps: 1
logging_strategy: steps
logging_steps: 1
num_train_epochs: 10
warmup_ratio: 0.01
use_liger: true