dataset_name: /project/flame/svadugur/learning-conventions/base_model_training_games/coco-4-images-listener
dataset_train_split: train
dataset_test_split: validation
output_dir: /project/flame/svadugur/learning-conventions/models/gemma_pt-coco-4-images-listener-feedback_label=true/lr=1e-4
run_name: gemma_pt-coco-4-images-listener-feedback_label=true
agent_type: listener
model_type: base
feedback_label: true
context_presentation: last_shuffle
max_seq_length: 16384
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
use_peft: true
lora_target_modules: all-linear
gradient_checkpointing: true
model_name_or_path: google/gemma-3-12b-pt
chat_template_file: agents/gemma-3-pt-chat-template.jinja
bf16: true
learning_rate: 1.0e-4
gradient_accumulation_steps: 8
torch_dtype: bfloat16
eval_on_start: true
eval_strategy: epoch
eval_steps: 1
save_strategy: epoch
save_steps: 1
logging_strategy: steps
logging_steps: 1
num_train_epochs: 5
warmup_ratio: 0.01
use_liger: true